---
- name: Copy file from GitHub without cloning
  hosts: 172.31.16.67
  gather_facts: true  # Mengumpulkan fakta tentang host
  become: yes

  tasks:
    - name: Clone GitHub repository
      git:
        repo: https://github.com/GuidoMario/ansible-playbook.git/test.txt
        dest: /home/guido/awx-operator

    - name: Copy file from cloned repository to target
      copy:
        src: /home/guido/awx-operator/test.txt  # Ganti dengan path relatif dari repositori yang telah diambil
        dest: /root/Documents  # Ganti dengan path tujuan di host target
