---
- name: Copy file from GitHub without cloning
  hosts: 172.31.16.67
  gather_facts: true  # Mengumpulkan fakta tentang host

  tasks:
    - name: Download file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/username/repo/master/path/to/your_file.txt  # Ganti dengan URL file di GitHub
        dest: /path/on/target/host/your_file.txt  # Ganti dengan path tujuan di host target
