---
- name: Copy file from GitHub without cloning
  hosts: 172.31.16.67
  gather_facts: true  # Mengumpulkan fakta tentang host

  tasks:
    - name: Download file from GitHub
      get_url:
        url: /test.txt
        dest: /root/Documents
