---
- name: Copy Text File to Remote Host
  hosts: 172.31.16.67 
  become: true

  tasks:
    - name: Copy text file to remote host
      copy:
        src: /home/guido/awx-operator/playbooks/test.txt  
        dest: /root/Documents
...
