---
- name: Copy Text File to Remote Host
  hosts: Host  # Gantilah dengan nama atau alamat IP host yang dituju
  become: true  # Menggunakan hak administratif (sudo)

  tasks:
    - name: Copy text file to remote host
      copy:
        src: /home/guido/awx-operator/playbooks/test.txt  # Gantilah dengan jalur file teks lokal
        dest: /root/Documents # Gantilah dengan jalur tujuan di host target
      become: true
