---
- name: Copy Text File to Remote Host
  hosts: 172.31.16.67 
  gather_facts: no
  become: yes

  tasks:
    - name: Copy text file to remote host
      copy:
        src: /home/guido/test.txt  
        dest: /root/Documents
...
